import {readGameFiles} from '../lib/imports';
const root=document.querySelector<HTMLElement>('#player')!;
const id=root.dataset.game!,engine=root.dataset.engine!;
const frame=document.querySelector<HTMLIFrameElement>('#game-frame')!;
const start=document.querySelector<HTMLButtonElement>('#start-game')!;
const status=document.querySelector<HTMLElement>('#player-status')!;
const launch=document.querySelector<HTMLElement>('#launch-panel')!;
let files:File[]=[],ready=false,timeout:ReturnType<typeof setTimeout>|undefined;
let pendingStart:((event:MessageEvent)=>void)|undefined;
const buttons=['stop-game','export-save','delete-save','import-save'];
const report=(message:string)=>{status.textContent=message;};
function enabled(value:boolean){ready=value;for(const name of buttons)(document.getElementById(name) as HTMLButtonElement).disabled=!value;}
for(const name of ['game-files','game-folder'])document.getElementById(name)?.addEventListener('change',e=>{files=Array.from((e.target as HTMLInputElement).files||[]);document.querySelector('#file-summary')!.textContent=files.length?`${files.length} files selected. Kept on your device.`:'No files selected.';});
start.addEventListener('click',async()=>{start.disabled=true;try{if(!('WebAssembly' in window))throw Error('This browser does not support WebAssembly.');report('Checking game files…');const assets=engine==='doom'&&id!=='freedoom'||engine==='quake'?await readGameFiles(files,engine):[];frame.src=`/engine/?game=${encodeURIComponent(id)}`;frame.hidden=false;launch.hidden=true;document.querySelector<HTMLButtonElement>('#stop-game')!.disabled=false;report('Downloading engine…');const send=(event:MessageEvent)=>{if(event.source===frame.contentWindow&&event.origin===location.origin&&event.data?.type==='shell-ready'){window.removeEventListener('message',send);pendingStart=undefined;frame.contentWindow!.postMessage({type:'start',game:id,assets},location.origin,assets.map(a=>a.bytes.buffer as ArrayBuffer));}};pendingStart=send;window.addEventListener('message',send);timeout=setTimeout(()=>{report('Startup is taking longer than expected. Check your connection or stop and try again.');},120000);}catch(error){report(error instanceof Error?error.message:'Could not start the game.');start.disabled=false;}});
window.addEventListener('message',event=>{if(event.source!==frame.contentWindow||event.origin!==location.origin)return;const msg=event.data;if(msg?.type==='stopped'){stop(msg.message||'Game stopped. Local saves synchronized.');}if(msg?.type==='operation-error'){enabled(true);report(msg.message);}if(msg?.type==='status')report(msg.message);if(msg?.type==='ready'){clearTimeout(timeout);enabled(true);report('Engine running. Click the game to focus controls.');}if(msg?.type==='error'){clearTimeout(timeout);enabled(false);report(msg.message);document.querySelector<HTMLButtonElement>('#stop-game')!.disabled=false;}if(msg?.type==='save-export'){const url=URL.createObjectURL(new Blob([JSON.stringify(msg.backup)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`decompgames-${id}-saves.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);report('Save backup exported.');}});
function stop(message:string){clearTimeout(timeout);if(pendingStart)window.removeEventListener('message',pendingStart);pendingStart=undefined;frame.src='about:blank';frame.hidden=true;launch.hidden=false;enabled(false);start.disabled=false;report(message);}
document.querySelector('#stop-game')!.addEventListener('click',()=>{if(!ready){stop('Game stopped.');return;}enabled(false);document.querySelector<HTMLButtonElement>('#stop-game')!.disabled=false;report('Saving browser data…');frame.contentWindow!.postMessage({type:'stop'},location.origin);});
document.querySelector('#fullscreen')!.addEventListener('click',()=>{document.querySelector('#stage')!.requestFullscreen().catch(()=>report('Fullscreen is unavailable in this browser.'));});
document.querySelector('#export-save')!.addEventListener('click',()=>{if(ready)frame.contentWindow!.postMessage({type:'export'},location.origin);});
document.querySelector('#delete-save')!.addEventListener('click',()=>{if(ready&&confirm('Delete this game’s local saves? Export a backup first. This cannot be undone.'))frame.contentWindow!.postMessage({type:'delete'},location.origin);});
document.querySelector('#import-save')!.addEventListener('change',async event=>{const input=event.target as HTMLInputElement;const file=input.files?.[0];if(!file||!ready)return;try{if(file.size>40*1024*1024)throw Error('Save backup file exceeds 40 MB.');const backup=JSON.parse(await file.text());if(backup.game!==id||backup.format!==1)throw Error('This backup belongs to another game or format.');if(confirm('Replace local saves with this backup? Export current saves first.'))frame.contentWindow!.postMessage({type:'import',backup},location.origin);}catch(error){report(error instanceof Error?error.message:'Invalid save backup.');}finally{input.value='';}});
