import {readFile,writeFile} from 'node:fs/promises';
const games=JSON.parse(await readFile('src/data/games.json','utf8'));
const notes={
 'tomb-raider':'OpenLara rebuilds the original Tomb Raider engine. Its browser technology is a useful starting point, but an upstream browser demo does not prove that a complete campaign works in this player. Keep level, audio, and video files from one supported game edition together. A single level file may omit music or cinematics. This catalog entry currently directs you to upstream setup instructions; local folder import and save compatibility still need an adapter here.',
 'duke-nukem-ii':'RigelEngine concentrates on Duke Nukem II rather than Duke Nukem 3D. It supports the original episodes and adds options such as widescreen presentation and quicksaves. Shareware contains only part of the campaign. Supply the data from the edition you own when following the upstream installation guide, and keep shareware and registered files separate. Our planned browser adapter will need to preserve the game directory and its save files; we have not certified that integration.',
 'openrct2':'OpenRCT2 expands the simulation engine for RollerCoaster Tycoon 2. The engine source does not include the original rides, scenery, scenarios, or sounds. Upstream installation uses RollerCoaster Tycoon 2 data; RollerCoaster Tycoon 1 content can add further assets when configured according to its guide. Native multiplayer support does not imply browser multiplayer support here. Browser file import, memory use on large parks, and save compatibility remain separate integration tasks.',
 'jazz-jackrabbit':'OpenJazz targets the original Jazz Jackrabbit, not Jazz Jackrabbit 2. Levels, graphics, and sound remain separate from its open engine. Different original releases contain different episodes, so a shareware installation should not be described as the full registered game. Follow the project’s file-layout instructions for your edition. A browser port needs more than a title-screen test: level transitions, movement timing, audio, and retained progress must also be checked.',
 'super-mario-64':'The sm64 project reconstructs the Nintendo 64 program from a supported original ROM. Its repository is a source and research project rather than a ready-to-play browser release. Building it involves a matching base ROM and the toolchain described upstream. ROM region and revision matter; a renamed or modified file is not interchangeable. We do not distribute Nintendo game assets. A future browser integration would need its own open-source port, local extraction, and documented controller and save tests.',
 'ocarina-of-time':'Ship of Harkinian builds on Ocarina of Time decompilation work and provides a modern port. Its asset extraction depends on supported original game versions; consult the current upstream list before preparing files. A port release, a source checkout, and an extracted asset archive serve different purposes. This page currently links to the project rather than accepting a ROM in the browser. Browser graphics, controller mapping, and save-file interchange have not been verified by Decomp Games.',
 'majoras-mask':'2 Ship 2 Harkinian brings Majora’s Mask to a modern source port. It is a separate project from Ship of Harkinian and requires its own supported game data. Ocarina of Time assets cannot substitute for it. Upstream extraction and release instructions are the authority for supported editions. This is a discovery listing, with no hosted Nintendo assets and no claim that desktop compatibility establishes browser support.',
 'star-fox-64':'Starship is a source port of Star Fox 64. The open project and the original game’s models, textures, music, and levels are separate. Use the exact game versions listed by its extraction instructions rather than assuming every regional release works. A browser integration would need sustained flight gameplay, controller calibration, audio, and persistent progress tests. Until those exist, this listing takes you to the upstream project.',
 'perfect-dark':'The Perfect Dark PC port is based on decompilation work and uses separately supplied original game data. Its native platform support is distinct from a browser build. Check the project’s supported ROM revisions and installation layout before extracting assets. We have not validated browser rendering, mission completion, controller behavior, or saves, and this listing does not serve a ROM or engine binary.',
 'sonic-1':'This listing concerns the Retro Engine version of Sonic the Hedgehog, rather than an emulator for the Mega Drive cartridge. It requires the matching release’s data archive. The project’s custom license is a separate question from whether its source can be read. Under this site’s hosting policy it remains a discovery entry while its license and any proposed hosted engine are reviewed. No Sega assets are bundled here.',
 'sonic-2':'The Sonic 2 Retro Engine decompilation uses assets from the supported Retro Engine release. Original console ROM files are not a drop-in replacement for that data. Keep Sonic 1 and Sonic 2 data archives separate even where they use related engine code. The custom engine terms and the proprietary game data have separate requirements. This page links to upstream instructions and does not offer a hosted browser build.',
 'sonic-cd':'The RSDKv3 project relates to the Retro Engine edition of Sonic CD. Its expected data format differs from the original console disc and later RSDK engine versions. Follow upstream edition and data-file requirements. Source visibility alone is not an open-source hosting approval under this catalog’s policy. Browser controls, audio, and save behavior are untested here, so this is a project listing.',
 'sonic-mania':'Sonic Mania uses its own game logic alongside the Retro Engine. The engine and game-logic repositories, their dependencies, and the retail data are separate pieces of an installation. Having one source checkout does not produce a complete redistributable game. Follow the upstream build and data instructions for your release. This catalog keeps the project discoverable while withholding hosted play under the current license policy.',
 'diablo':'DevilutionX reimplements and extends Diablo and Hellfire. The retail MPQ archives remain separate from the engine, and Hellfire content requires its own files. Shareware support should not be confused with a complete retail campaign. The project’s current licensing requires individual review for this site’s open-source hosting policy. We link to its installation guide while browser asset import, saves, and a hosting decision remain pending.',
 'dune-ii':'OpenDUNE recreates Dune II and expects data from the supported 1.07 release. The original executable can also be needed during preparation; simply copying a few PAK files may not satisfy the upstream instructions. Its GPL engine does not grant redistribution rights to the original artwork or audio. Start with the project’s native setup instructions. We have not tested a browser build, campaign progression, or save conversion.',
 'banjo-kazooie':'BanjoRecomp uses recompilation technology to run Banjo-Kazooie with modern platform support. Recompilation is listed separately from hand-reconstructed decompilation work so the catalog does not blur the two. Supported original game data is still required, with exact versions determined upstream. Native performance and controller support do not establish browser compatibility. We currently provide a source-project guide and no ROM download.'
};
for(const game of games){if(notes[game.id])game.overview=notes[game.id];}
const get=id=>games.find(g=>g.id===id);
get('freedoom').overview='Freedoom provides original artwork, levels, sounds, and music for open Doom engines. This player currently loads Phase 2 through Dwasm, using a software renderer. It does not require a commercial Doom WAD. Phase 1 is a separate campaign and is not selected by this player. The engine can also accept local WADs through the separate Doom entry.';
get('perfect-dark').source='https://github.com/perfect-dark-pc-port/perfect_dark';
get('super-mario-64').engineLicense='CC0-1.0';
get('banjo-kazooie').engineLicense='GPL-3.0';
get('openttd').limitations.push('Music synthesis is not enabled in the current browser build.');
get('beneath-a-steel-sky').limitations.push('This package is the floppy edition; spoken CD dialogue is not included.');
for(const id of ['open-cadet','freedoom','opentyrian']){
 const g=get(id);g.verification={status:'smoke-tested',date:'2026-09-18',browsers:['Chromium-based in-app browser on Windows'],scope:id==='freedoom'?'New-game menu, level start, firing, and save menu observed. Mouse capture, audible audio, and save round trip remain unverified.':'Engine startup and rendering observed. Gameplay, audible audio, and save persistence remain unverified.',playthrough:false};
}
await writeFile('src/data/games.json',JSON.stringify(games,null,2)+'\n');
