import {mkdir,writeFile} from 'node:fs/promises';
const seed=[
['open-cadet','Open Cadet',1995,'Arcade','Decompilation','instant','SpaceCadetPinball','Your next high score starts here. Classic space pinball, rebuilt with original open assets.','https://github.com/andrewnakas/open-cadet','MIT','CC0-1.0','cadet','#427fff'],
['openttd','OpenTTD',2004,'Strategy','Engine recreation','instant','OpenTTD','Build a transport empire. Connect towns with trains, roads, ships, and aircraft.','https://github.com/OpenTTD/OpenTTD','GPL-2.0-only','OpenGFX/OpenMSX: GPL-2.0; OpenSFX: CC-BY-SA-3.0','openttd','#50bb9b'],
['freedoom','Freedoom',2019,'Shooter','Source port','instant','Dwasm / PrBoom','Two original campaigns built for the Doom engine. Every map, sound, and sprite is free.','https://github.com/freedoom/freedoom','GPL-2.0-or-later (engine)','BSD-3-Clause (Freedoom)','doom','#c15c45'],
['opentyrian','OpenTyrian',1995,'Shooter','Engine recreation','instant','OpenTyrian','A vertical shooter with branching routes, ship upgrades, and a galaxy worth saving.','https://github.com/opentyrian/opentyrian','GPL-2.0-or-later','Tyrian 2.1 freeware; original assets retain their license','tyrian','#ac7ee6'],
['beneath-a-steel-sky','Beneath a Steel Sky',1994,'Adventure','Engine recreation','instant','ScummVM','Escape a dystopian city with a sharp-tongued robot and a very questionable plan.','https://github.com/scummvm/scummvm','GPL-3.0-or-later','Revolution Software freeware license','scummvm','#ce9a60','bass'],
['lure-of-the-temptress','Lure of the Temptress',1992,'Adventure','Engine recreation','instant','ScummVM','An unlikely hero, a village under siege, and characters with lives of their own.','https://github.com/scummvm/scummvm','GPL-3.0-or-later','Revolution Software freeware license','scummvm','#77a174','lure'],
['flight-of-the-amazon-queen','Flight of the Amazon Queen',1995,'Adventure','Engine recreation','instant','ScummVM','A crash landing sends pilot Joe King into a wonderfully improbable jungle adventure.','https://github.com/scummvm/scummvm','GPL-3.0-or-later','Flight of the Amazon Queen freeware license','scummvm','#d4a853','queen'],
['soltys','Sołtys',1995,'Adventure','Engine recreation','instant','ScummVM','Explore a mischievous Polish village in this hand-drawn point-and-click adventure.','https://github.com/scummvm/scummvm','GPL-3.0-or-later','L.K. Avalon freeware license','scummvm','#7596d2','soltys'],
['doom','Doom',1993,'Shooter','Source port','files','Dwasm / PrBoom','Bring your original WAD and return to the corridors that defined the first-person shooter.','https://github.com/GMH-Code/Dwasm','GPL-2.0-or-later','Original game data required','doom','#d2a766'],
['quake','Quake',1996,'Shooter','Source port','files','Qwasm','Slip through the slipgate. Play the original campaign with your own Quake PAK files.','https://github.com/GMH-Code/Qwasm','GPL-2.0-or-later','Original game data required','quake','#ad8762'],
['drascula','Drascula: The Vampire Strikes Back',1996,'Adventure','Engine recreation','project','ScummVM','A comic vampire adventure whose freeware release lives on through ScummVM.','https://github.com/scummvm/scummvm','GPL-3.0-or-later','Alcachofa Soft freeware license',null,'#a782af'],
['dreamweb','DreamWeb',1994,'Adventure','Engine recreation','project','ScummVM','A dark, top-down cyberpunk story with a distinctive inventory and exploration system.','https://github.com/scummvm/scummvm','GPL-3.0-or-later','DreamWeb freeware release',null,'#8586bb'],
['sfinx','Sfinx',1997,'Adventure','Engine recreation','project','ScummVM','Two young heroes investigate an alien arrival in this Polish adventure.','https://github.com/scummvm/scummvm','GPL-3.0-or-later','L.K. Avalon freeware license',null,'#62b5af'],
['the-griffon-legend','The Griffon Legend',2005,'Adventure','Engine recreation','project','ScummVM','A compact action adventure with exploration, swordplay, and hand-drawn pixel art.','https://github.com/scummvm/scummvm','GPL-3.0-or-later','Freeware release; see distribution terms',null,'#b58a68'],
['tomb-raider','Tomb Raider',1996,'Action','Engine recreation','project','OpenLara','Explore the OpenLara engine, its browser demonstration, and original-data requirements.','https://github.com/XProger/OpenLara','BSD-2-Clause','Original game data required',null,'#8baf8a'],
['duke-nukem-ii','Duke Nukem II',1993,'Platformer','Engine recreation','project','RigelEngine','A modern engine for all four episodes of the side-scrolling Duke Nukem adventure.','https://github.com/lethal-guitar/RigelEngine','GPL-2.0-or-later','Original game data or separately licensed shareware required',null,'#db8f56'],
['rollercoaster-tycoon-2','RollerCoaster Tycoon 2',2002,'Strategy','Engine recreation','project','OpenRCT2','Build and manage a theme park through an actively developed recreation of the original engine.','https://github.com/OpenRCT2/OpenRCT2','GPL-3.0-or-later','Original game data required',null,'#8cc57e'],
['jazz-jackrabbit','Jazz Jackrabbit',1994,'Platformer','Engine recreation','project','OpenJazz','A portable engine for the fast-moving original Jazz Jackrabbit, using your game data.','https://github.com/AlisterT/openjazz','GPL-2.0-or-later','Original game data required',null,'#76bb60'],
['super-mario-64','Super Mario 64',1996,'Platformer','Decompilation','project','sm64','Discover the landmark matching decompilation and the ports built on its reconstructed code.','https://github.com/n64decomp/sm64','See upstream; no blanket hosting permission assumed','Original ROM required',null,'#e78371'],
['ocarina-of-time','The Legend of Zelda: Ocarina of Time',1998,'Adventure','Decompilation','project','Ship of Harkinian','A native port with extensive controls, graphics options, and quality-of-life improvements.','https://github.com/HarbourMasters/Shipwright','See upstream component licenses','Supported original ROM required',null,'#93b57c'],
['majoras-mask','The Legend of Zelda: Majora’s Mask',2000,'Adventure','Decompilation','project','2Ship2Harkinian','A native Majora’s Mask port built on the community decompilation.','https://github.com/HarbourMasters/2ship2harkinian','CC0-1.0 and dependency licenses','Supported original ROM required',null,'#a08bbd'],
['star-fox-64','Star Fox 64',1997,'Shooter','Decompilation','project','Starship','Return to the Lylat system through the community’s native Star Fox 64 port.','https://github.com/HarbourMasters/Starship','CC0-1.0 and dependency licenses','Supported original ROM required',null,'#729eaa'],
['perfect-dark','Perfect Dark',2000,'Shooter','Decompilation','project','Perfect Dark PC','A work-in-progress native port of the Nintendo 64 shooter with modern platform support.','https://github.com/fgsfdsfgs/perfect_dark','MIT and dependency licenses','Supported original ROM required',null,'#b65c61'],
['sonic-1','Sonic the Hedgehog',2013,'Platformer','Decompilation','project','RSDKv4','Explore the reconstruction of Sonic’s 2013 version and the community ports it enables.','https://github.com/RSDKModding/RSDKv4-Decompilation','Source-available: noncommercial RSDK license','Official release assets required',null,'#6e9be3'],
['sonic-2','Sonic the Hedgehog 2',2013,'Platformer','Decompilation','project','RSDKv4','The 2013 Sonic 2 engine reconstruction, with original game assets supplied separately.','https://github.com/RSDKModding/RSDKv4-Decompilation','Source-available: noncommercial RSDK license','Official release assets required',null,'#e5bb65'],
['sonic-cd','Sonic CD',2011,'Platformer','Decompilation','project','RSDKv3','Find the Sonic CD 2011 decompilation and its documented asset requirements.','https://github.com/RSDKModding/RSDKv3-Decompilation','Source-available: noncommercial RSDK license','Official release assets required',null,'#77bcd4'],
['sonic-mania','Sonic Mania',2017,'Platformer','Decompilation','project','RSDKv5','A complete reconstruction of Sonic Mania’s game logic alongside the Retro Engine project.','https://github.com/RSDKModding/Sonic-Mania-Decompilation','Source-available: see upstream restrictions','Official release assets required',null,'#e58aa9'],
['diablo','Diablo',1996,'RPG','Decompilation','project','DevilutionX','A modern Diablo and Hellfire port with accessibility and quality-of-life improvements.','https://github.com/diasurgical/DevilutionX','Source-available: Sustainable Use License','DIABDAT.MPQ required for the full game',null,'#ba7163'],
['dune-ii','Dune II',1992,'Strategy','Engine recreation','project','OpenDUNE','An open recreation of the strategy game that helped define base-building RTS games.','https://github.com/OpenDUNE/OpenDUNE','GPL-2.0','Original game data required',null,'#c9a369'],
['banjo-kazooie','Banjo-Kazooie',1998,'Platformer','Recompilation','project','Banjo: Recompiled','A native recompilation that brings the bear-and-bird adventure to modern computers.','https://github.com/BanjoRecomp/BanjoRecomp','See upstream component licenses','Supported original ROM required',null,'#d0ad78']
];
const extra={
 'open-cadet':{overview:'Open Cadet pairs the reverse-engineered SpaceCadetPinball engine with an original neon playfield and synthesized sounds. It recreates the familiar table’s behavior without distributing Microsoft’s PINBALL.DAT. The replacement artwork is intentionally different from the Windows original.',controls:['Z — left flipper','/ — right flipper','Space — launch the ball','F2 — new game'],saveInstructions:'High scores and table settings are saved locally. A ball in progress is not a portable save state.',downloadMB:6.2,image:'/images/open-cadet.png'},
 'openttd':{overview:'Lay a railway, schedule trains, and grow a transport network over decades. This build uses community replacement graphics and music, so no Transport Tycoon Deluxe files are needed. Start with a small map while learning the interface.',controls:['Mouse — build and manage','Right drag — move the map','Mouse wheel — zoom'],saveInstructions:'Use the in-game Save menu, then export a backup from the player toolbar.',downloadMB:19,image:'/images/openttd.png',limitations:['Large maps require more memory.','Network multiplayer is not provided by this site.']},
 'freedoom':{overview:'Freedoom supplies new levels, artwork, sound, and music compatible with the Doom engine. It is a distinct free game, not a free copy of Doom. Choose a campaign and use the player’s save backup tools to move progress between browsers.',controls:['WASD — move','Mouse — look and fire','E — use','Esc — menu'],downloadMB:35,image:'/images/freedoom.png'},
 'beneath-a-steel-sky':{overview:'Robert Foster is taken from the wasteland to Union City, where a connected computer system controls everyday life. This is the freeware floppy edition, with text dialogue rather than CD speech. Use ScummVM’s menu to save before closing the player.',image:'/images/beneath-a-steel-sky.png',downloadMB:21},
 'lure-of-the-temptress':{overview:'Diermot wakes in captivity after a rebellion goes wrong. The adventure’s Virtual Theatre system lets other characters move through the village independently. The hosted release is Revolution’s freeware edition for ScummVM.',downloadMB:18},
 'flight-of-the-amazon-queen':{overview:'Pilot Joe King crash-lands in the Amazon and becomes entangled in a pulp adventure. The floppy edition keeps the initial download smaller; it uses text dialogue rather than the CD version’s voice acting.',downloadMB:35},
 'soltys':{overview:'An eccentric village is the setting for this comic adventure by L.K. Avalon. The English freeware edition runs through ScummVM’s CGE engine. Save from the game menu and keep an exported backup before clearing browser storage.',downloadMB:21},
 'doom':{assetRequirements:'Choose a compatible Doom IWAD (.wad), such as DOOM.WAD from your own installation. The commercial WAD is not supplied.',overview:'Dwasm runs the Doom engine directly as WebAssembly. Import your own IWAD to select the campaign. Start without mods; a working base game is easier to troubleshoot. Files are read locally and never uploaded.',downloadMB:3},
 'quake':{assetRequirements:'Choose PAK0.PAK and, for the registered campaign, PAK1.PAK from your original Quake installation. Remaster-specific packages are not assumed compatible.',overview:'Qwasm brings the original Quake engine to WebAssembly. Use the original game’s id1 packages, not an arbitrary remaster archive. The player accepts your local files and keeps save backups separate from copyrighted game data.',controls:['WASD — move','Mouse — look and fire','Space — jump','Esc — menu'],downloadMB:4},
 'opentyrian':{overview:'OpenTyrian recreates the Tyrian 2.1 engine, using the freeware release of the original data. Campaign progress includes your ship equipment and upgrades. This is the classic Tyrian content, not a claim to include every Tyrian 2000 addition.',controls:['Arrow keys — move','Space — fire','Enter — confirm','Esc — menu'],downloadMB:15}
};
const games=seed.map(([id,title,year,genre,kind,mode,engine,description,source,engineLicense,assetLicense,runtime,color,dataKey])=>({id,title,aliases:[engine],year,genre,kind,mode,engine,description,overview:`${description} This entry links to the upstream project so you can check supported releases, current compatibility, and installation instructions. A native desktop release does not establish browser compatibility.`,source,engineLicense,assetLicense,assetRequirements:mode==='instant'?'No original game files needed.':assetLicense,controls:genre==='Adventure'?['Left click — interact','Right click — alternate action','Ctrl + F5 — ScummVM menu']:['See the upstream project’s control documentation.'],saveInstructions:mode==='project'?'Follow the upstream project’s save instructions. There is no hosted player for this entry.':'Save through the in-game menu. Export a backup before clearing browser storage.',limitations:mode==='project'?['Directory entry; browser gameplay has not been verified here.']:['Browser integration is undergoing verification.'],inputs:mode==='project'?[]:['Keyboard','Mouse'],downloadMB:null,complete:mode==='instant'||mode==='files',color,runtime:runtime||undefined,dataKey,verification:{status:'unverified',date:null,browsers:[],scope:'Upstream documentation reviewed. No browser playthrough claimed.',playthrough:false},...extra[id]}));
await mkdir('src/data',{recursive:true});await writeFile('src/data/games.json',JSON.stringify(games,null,2)+'\n');
